
-- Buildings that give trade routes also extend the reach of amenities
INSERT OR REPLACE INTO Types (Type, Kind) VALUES ('BRMV_TRADE_BUILDING_LUXURY_EXTRA_AMENITIES', 'KIND_MODIFIER');
INSERT OR REPLACE INTO BuildingModifiers
    SELECT BuildingType, 'BRMV_TRADE_BUILDING_LUXURY_EXTRA_AMENITIES'
    FROM BuildingModifiers
    WHERE ModifierId LIKE '%TRADE_ROUTE_CAPACITY';
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType) 
    VALUES ('BRMV_TRADE_BUILDING_LUXURY_EXTRA_AMENITIES', 'MODIFIER_PLAYER_OWNED_LUXURY_EXTRA_AMENITIES');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Type, Value)
    VALUES ('BRMV_TRADE_BUILDING_LUXURY_EXTRA_AMENITIES', 'Amount', 'ARGTYPE_IDENTITY', 2);


